#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_DIR="${OPENCLAW_WORKSPACE:-$ROOT_DIR}"
DB_PATH="${WORKCTL_DB_PATH:-$ROOT_DIR/data/workos.db}"
PROJECTS_ROOT="${WORKCTL_PROJECTS_ROOT:-$WORKSPACE_DIR/work/projects}"
CUSTOMERS_ROOT="${WORKCTL_CUSTOMERS_ROOT:-$WORKSPACE_DIR/work/customers}"

rm -f "$DB_PATH"
rm -rf "$PROJECTS_ROOT" "$CUSTOMERS_ROOT"
mkdir -p "$ROOT_DIR/tmp"
printf 'smoke attachment\n' > "$ROOT_DIR/tmp/attachment.txt"

OPENCLAW_WORKSPACE="$WORKSPACE_DIR" \
WORKCTL_DB_PATH="$DB_PATH" \
WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" \
WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" \
"$ROOT_DIR/bin/workctl" init >/dev/null
sqlite3 "$DB_PATH" < "$ROOT_DIR/examples/demo-seed.sql"

OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" customer list >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" contact list --customer "Northwind Systems" >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" project list >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" offer list --customer "Northwind Systems" >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" offer item list --offer QDEMO001 >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" activity list --project PR0002 >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" task create --project PR0002 --title "Smoke task" --board delivery --column-key todo --wip-order 10 >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" task list --project PR0002 >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" task comment add --task 1 --body "smoke" >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" task status --task 1 --status in_progress --board delivery --column-key doing --wip-order 20 >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" attach add --entity-type task --entity-ref 1 --file "$ROOT_DIR/tmp/attachment.txt" --mime-type text/plain >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" attach list --entity-type task --entity-ref 1 >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" task show --task 1 >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" search --keyword northwind >/dev/null
OPENCLAW_WORKSPACE="$WORKSPACE_DIR" WORKCTL_DB_PATH="$DB_PATH" WORKCTL_PROJECTS_ROOT="$PROJECTS_ROOT" WORKCTL_CUSTOMERS_ROOT="$CUSTOMERS_ROOT" "$ROOT_DIR/bin/workctl" search --keyword smoke >/dev/null

echo "Smoke test passed"
